### PR TITLE
Use label selector to find operator statefulset

### LINKED ISSUE #47: Version detection code assumes fixed name for operator
The assumption that an operator running in a StatefulSet is always called `elastic-operator` is incorrect. We use different names for example in CI.

### PR DESCRIPTION
**Pull request by pebrc**
Fixes #47

### CODE REVIEW

File: internal/version.go [hunk 1]
```diff
@@ -39,15 +38,21 @@ func detectECKVersion(c *kubernetes.Clientset, namespace, userSpecifiedVersion s
 		}
 		return parsed
 	}
-	statefulSet, err := c.AppsV1().StatefulSets(namespace).Get(context.Background(), "elastic-operator", metav1.GetOptions{})
-	if apierrors.IsNotFound(err) {
-		return extractVersionFromDeployment(c, namespace)
-	}
+	// we use the control-plane label since ECK version 1.0
+	ssets, err := c.AppsV1().StatefulSets(namespace).List(context.Background(), metav1.ListOptions{LabelSelector: "control-plane=elastic-operator"})
```
Comment (thbkrkr) [inline internal/version.go:42]: Shouldn't we also do the same with a label selector in extractVersionFromDeployment ()?

Comment (pebrc) [reply internal/version.go:42]: We don't have those labels on the Deployment if it is generated by OLM only on the individual Pods

**Review by thbkrkr — APPROVED** [review]
LGTM
